name: gente_toxica_app
description: ViajeLibros package

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2 #was 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0" #was >=2.2.2

dependencies:
  flutter:
    sdk: flutter

  share: ^0.6.2+1
  #New Dependencies
  shared_preferences: ^0.5.3+5
  provider: ^3.1.0+1
  backdrop: ^0.1.8
  url_launcher: ^5.2.5
  flare_flutter: ^1.5.15
  flare_splash_screen: 3.0.0
  transparent_image: ^1.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/toxic.png
    - json/quotes_home.json
    - assets/icons/instagram-26.png
    - assets/icons/donar-26.png
    - assets/icons/beer-80.png
    #- toxic_splash_screen.flr
    - splash.flr
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoMono LightItalic
      fonts:
        - asset: assets/fonts/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
    - family: RobotoMono Regular
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
    - family: RobotoMono Medium
      fonts:
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
    - family: RobotoMono MediumItalic
      fonts:
        - asset: assets/fonts/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
    - family: RobotoMono Bold
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
    - family: RobotoMono BoldItalic
      fonts:
        - asset: assets/fonts/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
    - family: RobotoSlab Regular
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 400
    - family: RobotoSlab Light
      fonts:
        - asset: assets/fonts/RobotoSlab-Light.ttf
          weight: 300
    - family: RobotoMono Italic
      fonts:
        - asset: assets/fonts/RobotoMono-Italic.ttf
          weight: 400
          style: italic
    - family: Raleway
      fonts:
        #- asset: assets/fonts/Raleway-Regular.ttf
        #  style: normal
        #- asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
